/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.starwars;

/**
 *
 * @author vedatbilaloglu
 */
public class ChooseScreen extends javax.swing.JFrame {

    /**
     * Creates new form ChooseScreen
     */
    public ChooseScreen() {
        initComponents();
        this.setSize(400, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        masterYodaCheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        masterYodaImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lukeSkyCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        darthVaderCheck = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kyloCheck = new javax.swing.JCheckBox();
        stormCheck = new javax.swing.JCheckBox();
        startGameButton = new javax.swing.JButton();
        darthVaderImage = new javax.swing.JLabel();
        lukeSkywalkerImage = new javax.swing.JLabel();
        kyloRenImage = new javax.swing.JLabel();
        StormtrooperImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Choose Bad Chacaracter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 220, 210, 30);

        masterYodaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterYodaCheckActionPerformed(evt);
            }
        });
        getContentPane().add(masterYodaCheck);
        masterYodaCheck.setBounds(110, 190, 28, 23);

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Master Yoda");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 80, 16);

        masterYodaImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/masteryoda.jpg")); // NOI18N
        masterYodaImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterYodaImageMouseClicked(evt);
            }
        });
        getContentPane().add(masterYodaImage);
        masterYodaImage.setBounds(80, 50, 100, 110);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Luke Skywalker");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 170, 100, 16);

        lukeSkyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lukeSkyCheckActionPerformed(evt);
            }
        });
        getContentPane().add(lukeSkyCheck);
        lukeSkyCheck.setBounds(520, 190, 30, 23);

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Choose Good Chacaracter");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 20, 230, 20);

        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Darth Vader");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 390, 74, 16);

        darthVaderCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darthVaderCheckActionPerformed(evt);
            }
        });
        getContentPane().add(darthVaderCheck);
        darthVaderCheck.setBounds(70, 410, 30, 23);

        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Stormtrooper");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 390, 90, 16);

        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Kylo Ren");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 390, 60, 16);

        kyloCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kyloCheckActionPerformed(evt);
            }
        });
        getContentPane().add(kyloCheck);
        kyloCheck.setBounds(540, 410, 28, 23);

        stormCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stormCheckActionPerformed(evt);
            }
        });
        getContentPane().add(stormCheck);
        stormCheck.setBounds(320, 410, 28, 23);

        startGameButton.setBackground(new java.awt.Color(255, 255, 255));
        startGameButton.setForeground(new java.awt.Color(0, 102, 0));
        startGameButton.setText("START GAME");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startGameButton);
        startGameButton.setBounds(270, 450, 124, 40);

        darthVaderImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/darthvader.jpg")); // NOI18N
        darthVaderImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darthVaderImageMouseClicked(evt);
            }
        });
        getContentPane().add(darthVaderImage);
        darthVaderImage.setBounds(40, 270, 100, 110);

        lukeSkywalkerImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/Lukeskywalker.jpg")); // NOI18N
        lukeSkywalkerImage.setSize(new java.awt.Dimension(110, 110));
        lukeSkywalkerImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lukeSkywalkerImageMouseClicked(evt);
            }
        });
        getContentPane().add(lukeSkywalkerImage);
        lukeSkywalkerImage.setBounds(490, 50, 110, 110);

        kyloRenImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/kyloren.png")); // NOI18N
        kyloRenImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kyloRenImageMouseClicked(evt);
            }
        });
        getContentPane().add(kyloRenImage);
        kyloRenImage.setBounds(510, 270, 100, 110);

        StormtrooperImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/stormtrooper.jpg")); // NOI18N
        StormtrooperImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StormtrooperImageMouseClicked(evt);
            }
        });
        getContentPane().add(StormtrooperImage);
        StormtrooperImage.setBounds(280, 270, 110, 110);

        jLabel2.setText("Only One ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 50, 140, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stormCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stormCheckActionPerformed
        // TODO add your handling code here:
        if(stormCheck.isSelected()){
            System.out.println("storm checked");
        }
    }//GEN-LAST:event_stormCheckActionPerformed

    private void kyloCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kyloCheckActionPerformed
        // TODO add your handling code here:
        if(kyloCheck.isSelected()){
            System.out.println("kylo checked");
        }
    }//GEN-LAST:event_kyloCheckActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        
        
        CallPanel cp = new CallPanel("Game Screen");
        this.setVisible(false);
        
        
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void darthVaderCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darthVaderCheckActionPerformed
        // TODO add your handling code here:
        if(darthVaderCheck.isSelected()){
            System.out.println("darthVader checked");
        }
    }//GEN-LAST:event_darthVaderCheckActionPerformed

    private void masterYodaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterYodaCheckActionPerformed
        // TODO add your handling code here:
        if(masterYodaCheck.isSelected()){
            System.out.println("masterYoda checked");
            lukeSkyCheck.setSelected(false);
        }
    }//GEN-LAST:event_masterYodaCheckActionPerformed

    private void lukeSkyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lukeSkyCheckActionPerformed
        // TODO add your handling code here:
        if(lukeSkyCheck.isSelected()){
            System.out.println("lukeSky checked");
            masterYodaCheck.setSelected(false);
        }
    }//GEN-LAST:event_lukeSkyCheckActionPerformed

    private void lukeSkywalkerImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lukeSkywalkerImageMouseClicked
        
    }//GEN-LAST:event_lukeSkywalkerImageMouseClicked

    private void masterYodaImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterYodaImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masterYodaImageMouseClicked

    private void darthVaderImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darthVaderImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_darthVaderImageMouseClicked

    private void StormtrooperImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StormtrooperImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StormtrooperImageMouseClicked

    private void kyloRenImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kyloRenImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kyloRenImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StormtrooperImage;
    private javax.swing.JCheckBox darthVaderCheck;
    private javax.swing.JLabel darthVaderImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox kyloCheck;
    private javax.swing.JLabel kyloRenImage;
    private javax.swing.JCheckBox lukeSkyCheck;
    private javax.swing.JLabel lukeSkywalkerImage;
    private javax.swing.JCheckBox masterYodaCheck;
    private javax.swing.JLabel masterYodaImage;
    private javax.swing.JButton startGameButton;
    private javax.swing.JCheckBox stormCheck;
    // End of variables declaration//GEN-END:variables
}
