/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.starwars;

/**
 *
 * @author vedatbilaloglu
 */
public class ChooseScreen extends javax.swing.JFrame {

    /**
     * Creates new form ChooseScreen
     */
    public ChooseScreen() {
        initComponents();
        this.setSize(400, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterYodaImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        masterYodaCheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        lukeSkywalkerImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lukeSkyCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        darthVaderImage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        darthVaderCheck = new javax.swing.JCheckBox();
        StormtooperImage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kyloCheck = new javax.swing.JCheckBox();
        stormCheck = new javax.swing.JCheckBox();
        kyloRenImage = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        masterYodaImage.setBackground(new java.awt.Color(255, 51, 0));
        masterYodaImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/MP-YodaSpecies.png")); // NOI18N
        masterYodaImage.setText("jLabel2");
        getContentPane().add(masterYodaImage);
        masterYodaImage.setBounds(70, 50, 50, 90);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Choose Bad Chacaracter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 200, 210, 30);
        getContentPane().add(masterYodaCheck);
        masterYodaCheck.setBounds(80, 160, 28, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Master Yoda");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 80, 16);

        lukeSkywalkerImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/b8f4d12d1f2eb290a269f8ae9d4a8a7d.jpg")); // NOI18N
        lukeSkywalkerImage.setText("jLabel4");
        getContentPane().add(lukeSkywalkerImage);
        lukeSkywalkerImage.setBounds(260, 50, 50, 80);

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Luke Skywalker");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 140, 100, 16);
        getContentPane().add(lukeSkyCheck);
        lukeSkyCheck.setBounds(270, 160, 30, 23);

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("Choose Good Chacaracter");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 10, 230, 20);

        darthVaderImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/GUEST_bd945555-f106-40e9-80ad-4c6668b4e534.jpeg")); // NOI18N
        darthVaderImage.setText("jLabel7");
        getContentPane().add(darthVaderImage);
        darthVaderImage.setBounds(40, 230, 50, 90);

        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Darth Vader");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 310, 74, 16);
        getContentPane().add(darthVaderCheck);
        darthVaderCheck.setBounds(50, 330, 30, 23);

        StormtooperImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/p-082641-1.jpg")); // NOI18N
        StormtooperImage.setText("jLabel9");
        getContentPane().add(StormtooperImage);
        StormtooperImage.setBounds(170, 246, 50, 60);

        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Stormtrooper");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(153, 310, 90, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Kylo Ren");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 310, 60, 16);

        kyloCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kyloCheckActionPerformed(evt);
            }
        });
        getContentPane().add(kyloCheck);
        kyloCheck.setBounds(310, 330, 28, 23);

        stormCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stormCheckActionPerformed(evt);
            }
        });
        getContentPane().add(stormCheck);
        stormCheck.setBounds(180, 330, 28, 23);

        kyloRenImage.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/Kylo_Ren-_Advanced_Graphics-_TROS.png")); // NOI18N
        kyloRenImage.setText("jLabel13");
        getContentPane().add(kyloRenImage);
        kyloRenImage.setBounds(300, 250, 50, 60);

        startGameButton.setBackground(new java.awt.Color(0, 0, 153));
        startGameButton.setForeground(new java.awt.Color(0, 204, 204));
        startGameButton.setText("START GAME");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startGameButton);
        startGameButton.setBounds(130, 380, 124, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/vedatbilaloglu/Downloads/uzay-karanlik.jpg")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-7, 0, 410, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stormCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stormCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stormCheckActionPerformed

    private void kyloCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kyloCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kyloCheckActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        
        CallPanel cp = new CallPanel();
        cp.setVisible(true);
    }//GEN-LAST:event_startGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StormtooperImage;
    private javax.swing.JCheckBox darthVaderCheck;
    private javax.swing.JLabel darthVaderImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox kyloCheck;
    private javax.swing.JLabel kyloRenImage;
    private javax.swing.JCheckBox lukeSkyCheck;
    private javax.swing.JLabel lukeSkywalkerImage;
    private javax.swing.JCheckBox masterYodaCheck;
    private javax.swing.JLabel masterYodaImage;
    private javax.swing.JButton startGameButton;
    private javax.swing.JCheckBox stormCheck;
    // End of variables declaration//GEN-END:variables
}
